const titles={overview:'Genel Bakış',users:'Kullanıcılar',generations:'AI Üretimleri',credits:'Kredi & Gelir',providers:'AI Sağlayıcıları',ads:'Reklam & Paketler',moderation:'Moderasyon',system:'Sistem Sağlığı',settings:'Ayarlar'};
const demo={users:[['U-1042','creator@example.com','Pro','420','87','Aktif'],['U-1038','seller@example.com','Business','1260','241','Aktif'],['U-1027','demo@example.com','Free','18','14','Aktif'],['U-1011','risk@example.com','Free','0','3','İnceleme']],jobs:[['J-8841','Video','U-1042','CINEMATIC','70','Tamamlandı'],['J-8840','Image','U-1038','QUALITY','8','Tamamlandı'],['J-8839','Video','U-1038','FAST','30','İşleniyor'],['J-8838','Headshot','U-1027','QUALITY','20','Kuyrukta']],providers:[['FAST Router','Kısa video / düşük maliyet','Aktif'],['QUALITY Router','Görsel + premium çıktı','Aktif'],['CINEMATIC Router','Yüksek kalite video','Hazırlanıyor']]};
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+name)?.classList.add('active');document.querySelector(`[data-view="${name}"]`)?.classList.add('active');document.getElementById('pageTitle').textContent=titles[name]||'CreatorAI'}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.getElementById('refreshBtn').addEventListener('click',()=>toast('Demo verileri yenilendi'));
document.getElementById('connectBtn').addEventListener('click',()=>toast('Backend endpoint ve güvenli admin oturumu sonraki entegrasyonda bağlanacak.'));
document.querySelectorAll('[data-safe-action]').forEach(b=>b.addEventListener('click',()=>toast('Güvenli yazma işlemi için backend admin oturumu gerekli.')));
function badge(v){const ok=['Aktif','Tamamlandı'].includes(v);return `<span class="pill ${ok?'ok':v==='İnceleme'?'warn':''}">${v}</span>`}
document.getElementById('usersTable').innerHTML=demo.users.map(x=>`<tr><td><b>${x[0]}</b><br><small>${x[1]}</small></td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${badge(x[5])}</td><td><button class="ghost" data-safe-action="user">Yönet</button></td></tr>`).join('');
document.getElementById('jobsTable').innerHTML=demo.jobs.map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${badge(x[5])}</td></tr>`).join('');
document.getElementById('providerCards').innerHTML=demo.providers.map(x=>`<article class="card"><div class="card-head"><h3>${x[0]}</h3>${badge(x[2])}</div><p class="muted">${x[1]}</p><button class="ghost" data-safe-action="provider">Yapılandır</button></article>`).join('');
document.querySelectorAll('[data-safe-action]').forEach(b=>b.addEventListener('click',()=>toast('Bu işlem backend RBAC bağlantısından sonra aktif olacak.')));
document.getElementById('queueList').innerHTML='<div><span>Video işleri</span><b>12</b></div><div><span>Görsel işleri</span><b>5</b></div><div><span>Başarısız / iade</span><b>2</b></div>';
document.getElementById('costList').innerHTML='<div><span>Video maliyeti</span><b>₺14.820</b></div><div><span>Görsel maliyeti</span><b>₺4.820</b></div><div><span>Tahmini marj</span><b>%42</b></div>';
[['mUsers','12.480'],['mJobs','1.842'],['mCredits','48.260'],['mRevenue','₺58.190']].forEach(([id,v])=>document.getElementById(id).textContent=v);
const search=document.getElementById('userSearch');search?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();[...document.querySelectorAll('#usersTable tr')].forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')});
