const titles={overview:'Genel Bakış',users:'Kullanıcılar',generations:'AI Üretimleri',credits:'Kredi & Gelir',providers:'AI Sağlayıcıları',ads:'Reklam & Paketler',moderation:'Moderasyon',system:'Sistem Sağlığı',settings:'Ayarlar'};
const demo={users:[['U-1042','creator@example.com','Pro','420','87','Aktif'],['U-1038','seller@example.com','Business','1260','241','Aktif'],['U-1027','demo@example.com','Free','18','14','Aktif']],jobs:[['J-8841','Video','U-1042','CINEMATIC','70','Tamamlandı'],['J-8840','Image','U-1038','QUALITY','8','Tamamlandı'],['J-8839','Video','U-1038','FAST','30','İşleniyor']],providers:[['FAST Router','Kısa video / düşük maliyet','Aktif'],['QUALITY Router','Görsel + premium çıktı','Aktif'],['CINEMATIC Router','Yüksek kalite video','Hazırlanıyor']]};
const cfg={api:localStorage.getItem('veyra_api')||'',token:localStorage.getItem('veyra_admin_token')||''};
function toast(msg){const t=document.getElementById('toast');if(!t)return; t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+name)?.classList.add('active');document.querySelector(`[data-view="${name}"]`)?.classList.add('active');document.getElementById('pageTitle').textContent=titles[name]||'Veyra AI'}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
function badge(v){const ok=['Aktif','Tamamlandı','completed'].includes(v);return `<span class="pill ${ok?'ok':v==='İnceleme'?'warn':''}">${v}</span>`}
function renderDemo(){document.getElementById('usersTable').innerHTML=demo.users.map(x=>`<tr><td><b>${x[0]}</b><br><small>${x[1]}</small></td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${badge(x[5])}</td><td><button class="ghost" data-safe-action="user">Yönet</button></td></tr>`).join('');document.getElementById('jobsTable').innerHTML=demo.jobs.map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${badge(x[5])}</td></tr>`).join('');document.getElementById('providerCards').innerHTML=demo.providers.map(x=>`<article class="card"><div class="card-head"><h3>${x[0]}</h3>${badge(x[2])}</div><p class="muted">${x[1]}</p><button class="ghost" data-safe-action="provider">Yapılandır</button></article>`).join('');document.getElementById('queueList').innerHTML='<div><span>Video işleri</span><b>Demo</b></div><div><span>Görsel işleri</span><b>Demo</b></div>';document.getElementById('costList').innerHTML='<div><span>Backend</span><b>Bağlantı bekliyor</b></div>';[['mUsers','—'],['mJobs','—'],['mCredits','—'],['mRevenue','—']].forEach(([id,v])=>document.getElementById(id).textContent=v)}
async function api(path,opts={}){if(!cfg.api)throw new Error('API URL ayarlı değil');const headers={...(opts.headers||{}),'x-admin-token':cfg.token};const r=await fetch(cfg.api.replace(/\/$/,'')+path,{...opts,headers});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
async function refreshLive(){try{const health=await fetch(cfg.api.replace(/\/$/,'')+'/health').then(r=>r.json());const summary=await api('/v1/admin/summary');[['mUsers',summary.users],['mJobs',summary.jobs],['mCredits',summary.creditsOutstanding],['mRevenue','—']].forEach(([id,v])=>document.getElementById(id).textContent=v);document.getElementById('queueList').innerHTML=`<div><span>Kuyrukta</span><b>${summary.queued}</b></div><div><span>Tamamlanan</span><b>${summary.completed}</b></div><div><span>Ledger kayıtları</span><b>${summary.ledgerEntries}</b></div>`;document.getElementById('costList').innerHTML=`<div><span>Servis</span><b>${health.service}</b></div><div><span>Primary provider</span><b>${health.providers?.primary||'—'}</b></div><div><span>Uptime</span><b>${health.uptimeSeconds}s</b></div>`;toast('Canlı backend verileri yenilendi')}catch(e){toast('Backend bağlantısı başarısız');console.error(e)}}
document.getElementById('refreshBtn')?.addEventListener('click',()=>cfg.api?refreshLive():toast('Önce backend bağlantısını ayarla'));
document.getElementById('connectBtn')?.addEventListener('click',async()=>{const apiUrl=prompt('Veyra API URL',cfg.api||'https://your-api.example.com');if(!apiUrl)return;const token=prompt('Admin token',cfg.token||'');if(token===null)return;cfg.api=apiUrl.trim();cfg.token=token.trim();localStorage.setItem('veyra_api',cfg.api);localStorage.setItem('veyra_admin_token',cfg.token);await refreshLive()});
document.querySelectorAll('[data-safe-action]').forEach(b=>b.addEventListener('click',()=>toast('Yazma işlemleri RBAC + audit log sonrasında açılacak.')));
renderDemo();if(cfg.api&&cfg.token)refreshLive();
const search=document.getElementById('userSearch');search?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();[...document.querySelectorAll('#usersTable tr')].forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')});
