import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class VeyraLanguage {
  const VeyraLanguage(this.code, this.label, this.nativeLabel);
  final String code;
  final String label;
  final String nativeLabel;
}

const veyraLanguages = <VeyraLanguage>[
  VeyraLanguage('tr', 'Turkish', 'Türkçe'),
  VeyraLanguage('en', 'English', 'English'),
  VeyraLanguage('de', 'German', 'Deutsch'),
  VeyraLanguage('it', 'Italian', 'Italiano'),
  VeyraLanguage('ru', 'Russian', 'Русский'),
  VeyraLanguage('az', 'Azerbaijani', 'Azərbaycan dili'),
  VeyraLanguage('es', 'Spanish', 'Español'),
  VeyraLanguage('ar', 'Arabic', 'العربية'),
];

class VeyraLocaleController extends ValueNotifier<Locale> {
  VeyraLocaleController._() : super(const Locale('tr'));
  static final VeyraLocaleController instance = VeyraLocaleController._();
  static const _key = 'veyra_language';

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_key);
    if (saved != null && veyraLanguages.any((e) => e.code == saved)) {
      value = Locale(saved);
    }
  }

  Future<void> setLanguage(String code) async {
    if (!veyraLanguages.any((e) => e.code == code)) return;
    value = Locale(code);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, code);
  }
}

String vt(BuildContext context, String key) {
  final code = Localizations.localeOf(context).languageCode;
  final lang = _strings[code] ?? _strings['en']!;
  return lang[key] ?? _strings['en']![key] ?? key;
}

const Map<String, Map<String, String>> _strings = {
  'tr': {
    'studio': 'Studio','tools': 'Araçlar','projects': 'Projeler','profile': 'Profil','credits': 'kredi',
    'tagline': 'Create. Imagine. Inspire.','cloud_check': 'Sunucu kontrol ediliyor…','cloud_on': 'Veyra Cloud bağlı','cloud_off': 'Veyra Cloud çevrimdışı — tekrar denemek için dokun',
    'hero_title': 'Hayal et. Veyra AI üretsin.','hero_sub': 'Görsel, video, ürün reklamı ve profesyonel içerik üretimini tek stüdyoda yönet.','open_video': 'Video Studio’yu aç',
    'pro_sub': 'Premium modeller • yüksek kalite • reklamsız • ticari araçlar','ai_tools': 'AI araçları','all_tools': 'Tüm Veyra araçları','all_tools_sub': 'Her araç aynı Veyra Cloud kredi ve üretim kuyruğunu kullanır.',
    'video_title': 'Video Studio','video_sub': 'Metinden veya görselden sinematik video','image_title': 'Image Studio','image_sub': 'Görsel üret, düzenle ve geliştir',
    'product_title': 'Product Ads','product_sub': 'Ürününü profesyonel reklama dönüştür','headshot_title': 'Headshot AI','headshot_sub': 'Profesyonel portre ve profil stüdyosu',
    'magic_title': 'Magic Edit','magic_sub': 'İstediğin değişikliği metinle tarif et','enhance_title': 'Enhance & Upscale','enhance_sub': 'Kalite, netlik ve çözünürlük iyileştirme',
    'social_title': 'Social Creator','social_sub': 'Post, story ve reklam içerikleri','scene_title': 'Scene Director','scene_sub': 'Videoyu sahne sahne yönet',
    'prompt_for': 'için ne istiyorsun?','prompt_hint': 'Detaylı anlat: konu, stil, ışık, kamera, renkler, korunacak detaylar…','fast': 'Fast','pro': 'Pro','duration': 'Süre','seconds': 'saniye','audio_plan': 'Ses planı','audio_sub': 'Ambiyans, efekt ve konuşma yönlendirmesi',
    'calc_credit': 'Krediyi hesapla','processing': 'İşleniyor…','create': 'Veyra ile oluştur','cost_calc': 'Maliyet hesaplanıyor…','ready': 'Hazır','analyzing': 'Veyra isteğini analiz ediyor…','queueing': 'İş kuyruğa gönderiliyor…','job_created': 'İş oluşturuldu','server_error': 'Sunucu hatası','failed': 'İşlem başarısız','cloud_no': 'Veyra Cloud bağlantısı yok',
    'success_job': 'Veyra AI üretim işi başarıyla oluşturuldu.','job': 'Üretim işi','status': 'Durum','provider': 'Provider','cost': 'Maliyet','add_projects': 'Projelerime ekle','no_projects': 'Henüz proje yok. Bir AI aracı açıp ilk üretim işini oluştur.','status_failed': 'Durum alınamadı',
    'profile_title': 'Veyra AI Profil','test_user': 'Test Kullanıcısı','privacy': 'Gizlilik & Güvenlik','privacy_sub': 'API anahtarları cihazda tutulmaz; üretim istekleri Veyra Cloud üzerinden gider.','pro_account_sub': 'Abonelik ve satın alma ürünleri mağaza bağlantısından sonra aktif olacak.','language': 'Dil','language_sub': 'Uygulama dilini seç',
    'routing': 'Akıllı AI routing','hd_tools': 'HD / 4K araçları','secure': 'Güvenli mimari','commercial': 'Ticari araçlar',
  },
  'en': {
    'studio': 'Studio','tools': 'Tools','projects': 'Projects','profile': 'Profile','credits': 'credits','tagline': 'Create. Imagine. Inspire.',
    'cloud_check': 'Checking server…','cloud_on': 'Veyra Cloud connected','cloud_off': 'Veyra Cloud offline — tap to retry','hero_title': 'Imagine it. Veyra AI creates it.','hero_sub': 'Create images, videos, product ads and professional content in one studio.','open_video': 'Open Video Studio','pro_sub': 'Premium models • higher quality • no ads • commercial tools','ai_tools': 'AI tools','all_tools': 'All Veyra tools','all_tools_sub': 'Every tool uses the same Veyra Cloud credits and generation queue.',
    'video_title': 'Video Studio','video_sub': 'Cinematic video from text or image','image_title': 'Image Studio','image_sub': 'Generate, edit and enhance images','product_title': 'Product Ads','product_sub': 'Turn products into professional ads','headshot_title': 'Headshot AI','headshot_sub': 'Professional portraits and profile photos','magic_title': 'Magic Edit','magic_sub': 'Describe the exact change you want','enhance_title': 'Enhance & Upscale','enhance_sub': 'Improve quality, sharpness and resolution','social_title': 'Social Creator','social_sub': 'Posts, stories and ad content','scene_title': 'Scene Director','scene_sub': 'Control video scene by scene',
    'prompt_for': '— what do you want?','prompt_hint': 'Describe the subject, style, lighting, camera, colors and details to preserve…','fast': 'Fast','pro': 'Pro','duration': 'Duration','seconds': 'seconds','audio_plan': 'Audio plan','audio_sub': 'Ambience, effects and voice direction','calc_credit': 'Calculate credits','processing': 'Processing…','create': 'Create with Veyra','cost_calc': 'Calculating cost…','ready': 'Ready','analyzing': 'Veyra is analyzing your request…','queueing': 'Sending job to queue…','job_created': 'Job created','server_error': 'Server error','failed': 'Operation failed','cloud_no': 'No Veyra Cloud connection','success_job': 'Veyra AI generation job created successfully.','job': 'Generation job','status': 'Status','provider': 'Provider','cost': 'Cost','add_projects': 'Add to projects','no_projects': 'No projects yet. Open an AI tool and create your first generation job.','status_failed': 'Could not get status','profile_title': 'Veyra AI Profile','test_user': 'Test User','privacy': 'Privacy & Security','privacy_sub': 'API keys are never stored on the device; generation requests go through Veyra Cloud.','pro_account_sub': 'Subscriptions and purchases will activate after store integration.','language': 'Language','language_sub': 'Choose app language','routing': 'Smart AI routing','hd_tools': 'HD / 4K tools','secure': 'Secure architecture','commercial': 'Commercial tools',
  },
  'de': {
    'studio':'Studio','tools':'Werkzeuge','projects':'Projekte','profile':'Profil','credits':'Credits','tagline':'Create. Imagine. Inspire.','cloud_check':'Server wird geprüft…','cloud_on':'Veyra Cloud verbunden','cloud_off':'Veyra Cloud offline — tippen zum Wiederholen','hero_title':'Stell es dir vor. Veyra AI erstellt es.','hero_sub':'Bilder, Videos, Produktanzeigen und professionelle Inhalte in einem Studio.','open_video':'Video Studio öffnen','pro_sub':'Premium-Modelle • höhere Qualität • werbefrei • kommerzielle Tools','ai_tools':'AI-Werkzeuge','all_tools':'Alle Veyra-Werkzeuge','all_tools_sub':'Alle Werkzeuge nutzen dieselben Veyra-Cloud-Credits und dieselbe Warteschlange.','video_title':'Video Studio','video_sub':'Kinoreife Videos aus Text oder Bild','image_title':'Image Studio','image_sub':'Bilder erzeugen, bearbeiten und verbessern','product_title':'Product Ads','product_sub':'Produkte in professionelle Anzeigen verwandeln','headshot_title':'Headshot AI','headshot_sub':'Professionelle Porträts und Profilbilder','magic_title':'Magic Edit','magic_sub':'Beschreibe die gewünschte Änderung','enhance_title':'Enhance & Upscale','enhance_sub':'Qualität, Schärfe und Auflösung verbessern','social_title':'Social Creator','social_sub':'Posts, Stories und Werbeinhalte','scene_title':'Scene Director','scene_sub':'Video Szene für Szene steuern','prompt_for':'— was möchtest du?','prompt_hint':'Beschreibe Motiv, Stil, Licht, Kamera, Farben und wichtige Details…','fast':'Schnell','pro':'Pro','duration':'Dauer','seconds':'Sekunden','audio_plan':'Audioplan','audio_sub':'Atmosphäre, Effekte und Sprachrichtung','calc_credit':'Credits berechnen','processing':'Wird verarbeitet…','create':'Mit Veyra erstellen','cost_calc':'Kosten werden berechnet…','ready':'Bereit','analyzing':'Veyra analysiert deine Anfrage…','queueing':'Auftrag wird eingereiht…','job_created':'Auftrag erstellt','server_error':'Serverfehler','failed':'Vorgang fehlgeschlagen','cloud_no':'Keine Veyra-Cloud-Verbindung','success_job':'Veyra-AI-Auftrag wurde erstellt.','job':'Generierungsauftrag','status':'Status','provider':'Provider','cost':'Kosten','add_projects':'Zu Projekten hinzufügen','no_projects':'Noch keine Projekte. Öffne ein AI-Werkzeug und starte deinen ersten Auftrag.','status_failed':'Status konnte nicht geladen werden','profile_title':'Veyra AI Profil','test_user':'Testbenutzer','privacy':'Datenschutz & Sicherheit','privacy_sub':'API-Schlüssel werden nie auf dem Gerät gespeichert; Anfragen laufen über Veyra Cloud.','pro_account_sub':'Abos und Käufe werden nach der Store-Integration aktiviert.','language':'Sprache','language_sub':'App-Sprache wählen','routing':'Intelligentes AI-Routing','hd_tools':'HD-/4K-Werkzeuge','secure':'Sichere Architektur','commercial':'Kommerzielle Werkzeuge',
  },
  'it': {
    'studio':'Studio','tools':'Strumenti','projects':'Progetti','profile':'Profilo','credits':'crediti','tagline':'Create. Imagine. Inspire.','cloud_check':'Controllo server…','cloud_on':'Veyra Cloud connesso','cloud_off':'Veyra Cloud offline — tocca per riprovare','hero_title':'Immaginalo. Veyra AI lo crea.','hero_sub':'Crea immagini, video, annunci prodotto e contenuti professionali in un unico studio.','open_video':'Apri Video Studio','pro_sub':'Modelli premium • qualità superiore • niente pubblicità • strumenti commerciali','ai_tools':'Strumenti AI','all_tools':'Tutti gli strumenti Veyra','all_tools_sub':'Tutti gli strumenti usano gli stessi crediti e la stessa coda Veyra Cloud.','video_title':'Video Studio','video_sub':'Video cinematografici da testo o immagine','image_title':'Image Studio','image_sub':'Genera, modifica e migliora immagini','product_title':'Product Ads','product_sub':'Trasforma i prodotti in annunci professionali','headshot_title':'Headshot AI','headshot_sub':'Ritratti e foto profilo professionali','magic_title':'Magic Edit','magic_sub':'Descrivi esattamente la modifica desiderata','enhance_title':'Enhance & Upscale','enhance_sub':'Migliora qualità, nitidezza e risoluzione','social_title':'Social Creator','social_sub':'Post, storie e contenuti pubblicitari','scene_title':'Scene Director','scene_sub':'Controlla il video scena per scena','prompt_for':'— cosa vuoi creare?','prompt_hint':'Descrivi soggetto, stile, luce, camera, colori e dettagli da preservare…','fast':'Veloce','pro':'Pro','duration':'Durata','seconds':'secondi','audio_plan':'Piano audio','audio_sub':'Atmosfera, effetti e direzione vocale','calc_credit':'Calcola crediti','processing':'Elaborazione…','create':'Crea con Veyra','cost_calc':'Calcolo del costo…','ready':'Pronto','analyzing':'Veyra sta analizzando la richiesta…','queueing':'Invio alla coda…','job_created':'Lavoro creato','server_error':'Errore server','failed':'Operazione non riuscita','cloud_no':'Nessuna connessione a Veyra Cloud','success_job':'Lavoro Veyra AI creato con successo.','job':'Lavoro di generazione','status':'Stato','provider':'Provider','cost':'Costo','add_projects':'Aggiungi ai progetti','no_projects':'Nessun progetto. Apri uno strumento AI e crea il primo lavoro.','status_failed':'Impossibile ottenere lo stato','profile_title':'Profilo Veyra AI','test_user':'Utente test','privacy':'Privacy e sicurezza','privacy_sub':'Le chiavi API non vengono memorizzate sul dispositivo; le richieste passano da Veyra Cloud.','pro_account_sub':'Abbonamenti e acquisti saranno attivi dopo l’integrazione con lo store.','language':'Lingua','language_sub':'Scegli la lingua dell’app','routing':'Routing AI intelligente','hd_tools':'Strumenti HD / 4K','secure':'Architettura sicura','commercial':'Strumenti commerciali',
  },
  'ru': {
    'studio':'Студия','tools':'Инструменты','projects':'Проекты','profile':'Профиль','credits':'кредитов','tagline':'Create. Imagine. Inspire.','cloud_check':'Проверка сервера…','cloud_on':'Veyra Cloud подключён','cloud_off':'Veyra Cloud офлайн — нажмите для повтора','hero_title':'Представьте. Veyra AI создаст.','hero_sub':'Изображения, видео, реклама товаров и профессиональный контент в одной студии.','open_video':'Открыть Video Studio','pro_sub':'Премиум-модели • выше качество • без рекламы • коммерческие инструменты','ai_tools':'AI-инструменты','all_tools':'Все инструменты Veyra','all_tools_sub':'Все инструменты используют общие кредиты Veyra Cloud и очередь генерации.','video_title':'Video Studio','video_sub':'Кинематографичное видео из текста или изображения','image_title':'Image Studio','image_sub':'Создание, редактирование и улучшение изображений','product_title':'Product Ads','product_sub':'Профессиональная реклама для товаров','headshot_title':'Headshot AI','headshot_sub':'Профессиональные портреты и фото профиля','magic_title':'Magic Edit','magic_sub':'Опишите нужное изменение','enhance_title':'Enhance & Upscale','enhance_sub':'Повышение качества, резкости и разрешения','social_title':'Social Creator','social_sub':'Посты, истории и рекламный контент','scene_title':'Scene Director','scene_sub':'Управление видео по сценам','prompt_for':'— что вы хотите?','prompt_hint':'Опишите объект, стиль, свет, камеру, цвета и важные детали…','fast':'Быстро','pro':'Pro','duration':'Длительность','seconds':'секунд','audio_plan':'Аудиоплан','audio_sub':'Атмосфера, эффекты и голосовое направление','calc_credit':'Рассчитать кредиты','processing':'Обработка…','create':'Создать с Veyra','cost_calc':'Расчёт стоимости…','ready':'Готово','analyzing':'Veyra анализирует запрос…','queueing':'Задание отправляется в очередь…','job_created':'Задание создано','server_error':'Ошибка сервера','failed':'Операция не выполнена','cloud_no':'Нет соединения с Veyra Cloud','success_job':'Задание Veyra AI успешно создано.','job':'Задание генерации','status':'Статус','provider':'Провайдер','cost':'Стоимость','add_projects':'Добавить в проекты','no_projects':'Проектов пока нет. Откройте AI-инструмент и создайте первое задание.','status_failed':'Не удалось получить статус','profile_title':'Профиль Veyra AI','test_user':'Тестовый пользователь','privacy':'Конфиденциальность и безопасность','privacy_sub':'API-ключи не хранятся на устройстве; запросы идут через Veyra Cloud.','pro_account_sub':'Подписки и покупки будут активированы после интеграции со стором.','language':'Язык','language_sub':'Выберите язык приложения','routing':'Умная маршрутизация AI','hd_tools':'HD / 4K инструменты','secure':'Безопасная архитектура','commercial':'Коммерческие инструменты',
  },
  'az': {
    'studio':'Studio','tools':'Alətlər','projects':'Layihələr','profile':'Profil','credits':'kredit','tagline':'Create. Imagine. Inspire.','cloud_check':'Server yoxlanılır…','cloud_on':'Veyra Cloud qoşulub','cloud_off':'Veyra Cloud oflayndır — yenidən yoxlamaq üçün toxun','hero_title':'Təsəvvür et. Veyra AI yaratsın.','hero_sub':'Şəkil, video, məhsul reklamı və peşəkar məzmunu bir studiyada yarat.','open_video':'Video Studio-nu aç','pro_sub':'Premium modellər • yüksək keyfiyyət • reklamsız • kommersiya alətləri','ai_tools':'AI alətləri','all_tools':'Bütün Veyra alətləri','all_tools_sub':'Bütün alətlər eyni Veyra Cloud kreditlərini və istehsal növbəsini istifadə edir.','video_title':'Video Studio','video_sub':'Mətndən və ya şəkildən sinematik video','image_title':'Image Studio','image_sub':'Şəkil yarat, redaktə et və yaxşılaşdır','product_title':'Product Ads','product_sub':'Məhsulu peşəkar reklama çevir','headshot_title':'Headshot AI','headshot_sub':'Peşəkar portret və profil studiyası','magic_title':'Magic Edit','magic_sub':'İstədiyin dəyişikliyi təsvir et','enhance_title':'Enhance & Upscale','enhance_sub':'Keyfiyyət, aydınlıq və ölçünü artır','social_title':'Social Creator','social_sub':'Post, story və reklam məzmunu','scene_title':'Scene Director','scene_sub':'Videonu səhnə-səhnə idarə et','prompt_for':'üçün nə istəyirsən?','prompt_hint':'Mövzu, stil, işıq, kamera, rənglər və qorunacaq detalları yaz…','fast':'Sürətli','pro':'Pro','duration':'Müddət','seconds':'saniyə','audio_plan':'Səs planı','audio_sub':'Ambians, effekt və səs istiqaməti','calc_credit':'Krediti hesabla','processing':'İşlənir…','create':'Veyra ilə yarat','cost_calc':'Xərc hesablanır…','ready':'Hazır','analyzing':'Veyra istəyini analiz edir…','queueing':'Tapşırıq növbəyə göndərilir…','job_created':'Tapşırıq yaradıldı','server_error':'Server xətası','failed':'Əməliyyat uğursuz oldu','cloud_no':'Veyra Cloud bağlantısı yoxdur','success_job':'Veyra AI tapşırığı uğurla yaradıldı.','job':'İstehsal tapşırığı','status':'Status','provider':'Provider','cost':'Xərc','add_projects':'Layihələrə əlavə et','no_projects':'Hələ layihə yoxdur. AI aləti aç və ilk tapşırığı yarat.','status_failed':'Status alınmadı','profile_title':'Veyra AI Profil','test_user':'Test istifadəçisi','privacy':'Məxfilik və Təhlükəsizlik','privacy_sub':'API açarları cihazda saxlanmır; sorğular Veyra Cloud üzərindən gedir.','pro_account_sub':'Abunəlik və alışlar mağaza inteqrasiyasından sonra aktiv olacaq.','language':'Dil','language_sub':'Tətbiq dilini seç','routing':'Ağıllı AI yönləndirmə','hd_tools':'HD / 4K alətləri','secure':'Təhlükəsiz arxitektura','commercial':'Kommersiya alətləri',
  },
  'es': {
    'studio':'Estudio','tools':'Herramientas','projects':'Proyectos','profile':'Perfil','credits':'créditos','tagline':'Create. Imagine. Inspire.','cloud_check':'Comprobando servidor…','cloud_on':'Veyra Cloud conectado','cloud_off':'Veyra Cloud sin conexión — toca para reintentar','hero_title':'Imagínalo. Veyra AI lo crea.','hero_sub':'Crea imágenes, videos, anuncios de producto y contenido profesional en un solo estudio.','open_video':'Abrir Video Studio','pro_sub':'Modelos premium • mayor calidad • sin anuncios • herramientas comerciales','ai_tools':'Herramientas AI','all_tools':'Todas las herramientas de Veyra','all_tools_sub':'Todas las herramientas usan los mismos créditos y la misma cola de Veyra Cloud.','video_title':'Video Studio','video_sub':'Video cinematográfico desde texto o imagen','image_title':'Image Studio','image_sub':'Genera, edita y mejora imágenes','product_title':'Product Ads','product_sub':'Convierte productos en anuncios profesionales','headshot_title':'Headshot AI','headshot_sub':'Retratos y fotos de perfil profesionales','magic_title':'Magic Edit','magic_sub':'Describe exactamente el cambio que quieres','enhance_title':'Enhance & Upscale','enhance_sub':'Mejora calidad, nitidez y resolución','social_title':'Social Creator','social_sub':'Posts, historias y contenido publicitario','scene_title':'Scene Director','scene_sub':'Controla el video escena por escena','prompt_for':'— ¿qué quieres crear?','prompt_hint':'Describe sujeto, estilo, luz, cámara, colores y detalles a conservar…','fast':'Rápido','pro':'Pro','duration':'Duración','seconds':'segundos','audio_plan':'Plan de audio','audio_sub':'Ambiente, efectos y dirección de voz','calc_credit':'Calcular créditos','processing':'Procesando…','create':'Crear con Veyra','cost_calc':'Calculando coste…','ready':'Listo','analyzing':'Veyra está analizando tu solicitud…','queueing':'Enviando trabajo a la cola…','job_created':'Trabajo creado','server_error':'Error del servidor','failed':'Operación fallida','cloud_no':'Sin conexión a Veyra Cloud','success_job':'Trabajo de Veyra AI creado correctamente.','job':'Trabajo de generación','status':'Estado','provider':'Proveedor','cost':'Coste','add_projects':'Añadir a proyectos','no_projects':'Aún no hay proyectos. Abre una herramienta AI y crea tu primer trabajo.','status_failed':'No se pudo obtener el estado','profile_title':'Perfil de Veyra AI','test_user':'Usuario de prueba','privacy':'Privacidad y seguridad','privacy_sub':'Las claves API nunca se guardan en el dispositivo; las solicitudes pasan por Veyra Cloud.','pro_account_sub':'Las suscripciones y compras se activarán tras integrar la tienda.','language':'Idioma','language_sub':'Elige el idioma de la app','routing':'Enrutamiento AI inteligente','hd_tools':'Herramientas HD / 4K','secure':'Arquitectura segura','commercial':'Herramientas comerciales',
  },
  'ar': {
    'studio':'الاستوديو','tools':'الأدوات','projects':'المشاريع','profile':'الملف الشخصي','credits':'رصيد','tagline':'Create. Imagine. Inspire.','cloud_check':'جارٍ فحص الخادم…','cloud_on':'Veyra Cloud متصل','cloud_off':'Veyra Cloud غير متصل — اضغط لإعادة المحاولة','hero_title':'تخيّلها. Veyra AI ينشئها.','hero_sub':'أنشئ الصور والفيديوهات وإعلانات المنتجات والمحتوى الاحترافي في استوديو واحد.','open_video':'فتح Video Studio','pro_sub':'نماذج مميزة • جودة أعلى • بدون إعلانات • أدوات تجارية','ai_tools':'أدوات الذكاء الاصطناعي','all_tools':'جميع أدوات Veyra','all_tools_sub':'تستخدم كل الأدوات نفس رصيد Veyra Cloud ونفس قائمة الانتظار.','video_title':'Video Studio','video_sub':'فيديو سينمائي من نص أو صورة','image_title':'Image Studio','image_sub':'إنشاء الصور وتحريرها وتحسينها','product_title':'Product Ads','product_sub':'حوّل المنتجات إلى إعلانات احترافية','headshot_title':'Headshot AI','headshot_sub':'صور شخصية وملفات احترافية','magic_title':'Magic Edit','magic_sub':'صف التغيير الذي تريده بدقة','enhance_title':'Enhance & Upscale','enhance_sub':'تحسين الجودة والوضوح والدقة','social_title':'Social Creator','social_sub':'منشورات وقصص ومحتوى إعلاني','scene_title':'Scene Director','scene_sub':'تحكم بالفيديو مشهداً بعد مشهد','prompt_for':'— ماذا تريد؟','prompt_hint':'صف الموضوع والأسلوب والإضاءة والكاميرا والألوان والتفاصيل المهمة…','fast':'سريع','pro':'Pro','duration':'المدة','seconds':'ثوانٍ','audio_plan':'خطة الصوت','audio_sub':'الأجواء والمؤثرات وتوجيه الصوت','calc_credit':'حساب الرصيد','processing':'جارٍ المعالجة…','create':'إنشاء بواسطة Veyra','cost_calc':'جارٍ حساب التكلفة…','ready':'جاهز','analyzing':'Veyra يحلل طلبك…','queueing':'جارٍ إرسال المهمة إلى قائمة الانتظار…','job_created':'تم إنشاء المهمة','server_error':'خطأ في الخادم','failed':'فشلت العملية','cloud_no':'لا يوجد اتصال بـ Veyra Cloud','success_job':'تم إنشاء مهمة Veyra AI بنجاح.','job':'مهمة التوليد','status':'الحالة','provider':'المزود','cost':'التكلفة','add_projects':'إضافة إلى المشاريع','no_projects':'لا توجد مشاريع بعد. افتح أداة AI وأنشئ أول مهمة.','status_failed':'تعذر جلب الحالة','profile_title':'ملف Veyra AI','test_user':'مستخدم تجريبي','privacy':'الخصوصية والأمان','privacy_sub':'لا يتم تخزين مفاتيح API على الجهاز؛ تمر الطلبات عبر Veyra Cloud.','pro_account_sub':'سيتم تفعيل الاشتراكات والمشتريات بعد ربط المتجر.','language':'اللغة','language_sub':'اختر لغة التطبيق','routing':'توجيه AI ذكي','hd_tools':'أدوات HD / 4K','secure':'بنية آمنة','commercial':'أدوات تجارية',
  },
};
